"""add columns

Revision ID: f1fbc1fa997f
Revises: c2ff6e74c6d1
Create Date: 2024-09-05 16:10:32.040690+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fbc1fa997f'
down_revision = 'c2ff6e74c6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
