FROM ubuntu

RUN apt-get update
#RUN apt-get install -y nginx
RUN apt-get install -y iputils-ping net-tools


#COPY ./conf/default.conf /etc/nginx/sites-available/default
#COPY ./html/ /var/www/html/

#ENTRYPOINT /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
#ENTRYPOINT ["echo", "Hello"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]


#CMD ["bash"]

